﻿// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PocketMenuUI.Data;

namespace PocketMenuUI.Migrations
{
    [DbContext(typeof(JelovnikDbContext))]
    partial class JelovnikDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PocketMenuUI.Models.Beverage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Beverages");
                });

            modelBuilder.Entity("PocketMenuUI.Models.Meal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Ingredients")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Amount = 1,
                            Ingredients = "Sauce,Lettuce,Leafs",
                            Price = 18.0,
                            Title = "Salad"
                        },
                        new
                        {
                            ID = 2,
                            Amount = 1,
                            Ingredients = "Cheese,Ham,Tomato sauce",
                            Price = 33.0,
                            Title = "Pizza"
                        },
                        new
                        {
                            ID = 3,
                            Amount = 1,
                            Ingredients = "Meat,sauce",
                            Price = 26.0,
                            Title = "Spaghetti bolognese"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
